name = "ComposableCommands"
uuid = "b5b47461-4a42-4db3-bdf2-684fadd57bc3"
version = "0.3.0"
authors = ["singularitti <singularitti@outlook.com> and contributors"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StructEqualHash = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"

[compat]
AbstractTrees = "0.4.5"
OrderedCollections = "1"
StructEqualHash = "0.1.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
